### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by spassvogel** [spassvogel/yuri#1]
Quick todo:

- [ ] animate between slides
- [x] show feedback when slideshow starts and ends
- [x] manual move forward and back
- [x] scroll to image when manual moving
- [ ] background as blurred image
- [ ] preloader

**Comment by spassvogel** [comment]
**show feedback when slideshow starts and ends**


https://www.npmjs.com/package/font-awesome-webpack
http://fontawesome.io/icon/pause-circle/
http://stackoverflow.com/questions/21406538/how-to-use-font-awesome-icons-from-node-modules

**Comment by spassvogel** [comment]
**preloader**

http://fontawesome.io/examples/#animated
